on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: locaweb/ftp-deploy@1.0.0
      with:
            host: ${{ secrets.HOST }} 
            user: ${{ secrets.USER }}
            password: ${{ secrets.PASS }}
